### ISSUE TITLE
Stop custom node when stopping the dataflow

### ISSUE THREAD

**Issue by phil-opp** [dora-rs/dora#136] opened 2022-11-09 13:26 UTC
Requested by @haixuanTao

**Comment by phil-opp** [comment] 2022-11-09 13:27
@haixuanTao Could you give more details on this request?

**Comment by haixuanTao** [comment] 2022-11-09 16:09
The problem is that some python program such as ROS python nodes are based on a forever loop. When starting them through dora we might want to stop them on `dora stop`.

**Comment by haixuanTao** [comment] 2022-11-09 16:10
But after discussion, we chose to leave the closing of those forever loops to the user as we might not have enough information on how to stop the nodes.

**Comment by phil-opp** [comment] 2023-03-09 12:25
With the new event stream design merged in #162, all nodes should listen for incoming events, even if they don't expect inputs. Nodes that don't do this will be killed as soon as #184 is merged.

**Comment by haixuanTao** [comment] 2024-08-31 04:49
Closing as rhis is now implemented with grace duration

**Closed by haixuanTao** 2024-08-31 04:49 UTC
Labels: cli
