### ISSUE TITLE
no node exists at `../../target/debug/rust-dataflow-url-example-sink`: No such file or directory

### ISSUE THREAD

**Issue by meua** [dora-rs/dora#294] opened 2023-05-22 12:07 UTC
**Describe the bug**
Could not validate yaml: Dataflow could not be validated.: no node exists at `../../target/debug/rust-dataflow-url-example-sink`: No such file or directory (os error 2)
```bash
(dora3.7) jarvis@jia:~/coding/dora_home/dora/binaries/cli/src$ cargo run start ../../../examples/rust-dataflow-url/dataflow.yml --attach --hot-reload
   Compiling dora-operator-api-c v0.2.3-rc6 (/home/jarvis/coding/dora_home/dora/apis/c/operator)
   Compiling dora-cli v0.2.3-rc6 (/home/jarvis/coding/dora_home/dora/binaries/cli)
    Finished dev [unoptimized + debuginfo] target(s) in 3.97s
     Running `/home/jarvis/coding/dora_home/dora/target/debug/dora-cli start ../../../examples/rust-dataflow-url/dataflow.yml --attach --hot-reload`
Could not validate yaml: Dataflow could not be validated.: no node exists at `../../target/debug/rust-dataflow-url-example-sink`: No such file or directory (os error 2)
(dora3.7) jarvis@jia:~/coding/dora_home/dora/binaries/cli/src$ 

```

**To Reproduce**
1. Dora start daemon: `dora up` 
2. Start a new dataflow: `dora start  examples/rust-dataflow-url/dataflow.yml --attach --hot-reload`

**Environments (please complete the following information):**
 - System info: ubuntu 22.04
 - Dora version: dora v0.2.3-rc6

**Comment by meua** [comment] 2023-05-22 12:23
And rust-dataflow-url module is not included in module tree, This module code appears to be out of date.

**Comment by haixuanTao** [comment] 2023-05-24 10:44
This is a duplicate of #192.

**Closed by haixuanTao** 2023-05-24 10:44 UTC
Labels: bug, cli, rust, daemon, linux
