### ISSUE TITLE
The process cannot be destroyed by the command `dora destroy`

### ISSUE THREAD

**Issue by meua** [dora-rs/dora#260] opened 2023-04-21 10:52 UTC
**Describe the bug**
The process cannot be destroyed by the command `dora destroy`

**To Reproduce**
1. Dora start daemon: `dora up` 
2. Destroy dataflow: `dora destroy`

**Screenshots or Video**
![image](https://user-images.githubusercontent.com/11570442/233615442-455ca602-ac62-4233-b1c3-ab47c1b51f03.png)

**Environments (please complete the following information):**
 - System info: ubuntu 20.04
 - Dora version: 0.2.2

**Comment by haixuanTao** [comment] 2023-04-25 08:38
Can you redo the exact same command but setting `export RUST_LOG=trace` before running them?

**Comment by meua** [comment] 2023-04-28 09:51
> Can you redo the exact same command but setting `export RUST_LOG=trace` before running them?

Ok, I got it, I'll do it and give you feedback.

**Comment by haixuanTao** [comment] 2024-08-31 04:50
I think this is a duplicate of #253

**Closed by haixuanTao** 2024-08-31 04:50 UTC
Labels: bug, cli
