### ISSUE TITLE
error[E0277]: the trait bound `DataSample: From<dora_operator_api_types::safer_ffi::Vec<u8>>` is not satisfied

### ISSUE THREAD

**Issue by pgchui** [dora-rs/dora#355] opened 2023-09-14 02:26 UTC
**Describe the bug**
I was following instructions here (https://dora.carsmos.ai/docs/guides/Installation/installing#cargo-and-pip) to install dora-rs using cargo. When executing `cargo install dora-daemon`, I encountered 
```
error[E0277]: the trait bound `DataSample: From<dora_operator_api_types::safer_ffi::Vec<u8>>` is not satisfied
   --> /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dora-runtime-0.2.5/src/operator/shared_lib.rs:127:44
    |
127 |                 data: Some(data.to_owned().into()),
    |                                            ^^^^ the trait `From<dora_operator_api_types::safer_ffi::Vec<u8>>` is not implemented for `DataSample`
    |
    = help: the trait `From<std::vec::Vec<u8>>` is implemented for `DataSample`
    = note: required for `dora_operator_api_types::safer_ffi::Vec<u8>` to implement `Into<DataSample>`

For more information about this error, try `rustc --explain E0277`.
error: could not compile `dora-runtime` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `dora-daemon v0.2.5`, intermediate artifacts can be found at `/tmp/cargo-installpVjJSx`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.

```

**To Reproduce**
1. `cargo install dora-cli`
2. `alias dora='dora-cli'`
3. `cargo install dora-coordinator`
4. `cargo install dora-daemon`

**Expected behavior**
Successful installation of 'dora-daemon'

**Screenshots or Video**

![Screenshot from 2023-09-13 22-23-30](https://github.com/dora-rs/dora/assets/25329580/0ffac246-3610-4eb3-8996-c662b475f5d8)

**Environments (please complete the following information):**
 - System info: Linux dev-TensorBook-2022 5.15.0-83-generic #92-Ubuntu SMP Mon Aug 14 09:30:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

 - Dora version: dora-cli 0.2.5

**Additional context**
N/A

**Comment by phil-opp** [comment] 2023-09-14 08:16
Thanks for reporting! This should be fixed by #354, I'll prepare a new release in a moment. Until then, you can use `cargo install dora-daemon --locked` as a workaround.

## Details

The issue is quite subtle:

- The `safer-ffi` crate added a `Clone` implmentation for their `safer_ffi::Vec` type in https://github.com/getditto/safer_ffi/commit/34c73c44dc492d567a305626ae2eb4458d01c77b and released this change in `v0.1.3`. 
- The `data.to_owned()` call in our code uses the [`ToOwned` trait](https://doc.rust-lang.org/stable/std/borrow/trait.ToOwned.html) of the standard library, which has a [blanket implementation for all clonable types](https://doc.rust-lang.org/stable/std/borrow/trait.ToOwned.html#impl-ToOwned-for-T)
- In older `safer-ffi` releases, `safer_ffi::Vec` was not `Clone`, so it didn't implement the `ToOwned` trait either. Thus, the compiler dereferenced it to a byte slice and used the [`ToOwned` implementation for `[u8]`](https://doc.rust-lang.org/stable/std/borrow/trait.ToOwned.html), which resulted in a `std::vec::Vec`.
- So the type of `data.to_owned()` changed from `std::vec::Vec` to `safer_ffi::Vec` just by upgrading the dependency. Only the former has an `Into` conversion to `DataSample`, so the dependency upgrade led to a build error.
- The reason that a dependency update occurs is that `cargo install` automatically installs the latest patch versions of all dependencies, ignoring the `Cargo.lock`. The workaround is to pass the `--locked` argument, which uses the exact versions specified in the `Cargo.lock` (including the older `safer-ffi` release).

**Closed** 2023-09-14 09:02 UTC
Labels: bug, documentation, cli, rust, runtime, daemon, coordinator
